###
POST http://localhost:8080/municipios
Content-Type: application/json
Accept: application/json

{
    "nome": "Maceió",
    "populacao": 1230912
}

###
GET http://localhost:8080/municipios?idUF=4
Accept: application/json

Open Liberty
###
GET http://localhost:9080/municipios?idUF=41
Accept: application/json

###
GET http://localhost:8080/mp-restclient?idUF=10


Liberty
###
GET http://localhost:9080/mp-restclient?idUF=100

quarkus
###
GET http://localhost:8080/mp-restclient?idUF=100

Liberty
###
GET http://localhost:9080/mp-restclient/com-service-intermediario?idUF=100

quarkus
###
GET http://localhost:8080/mp-restclient/com-service-intermediario?idUF=100


###
GET http://localhost:8080/mp-restclient/sem-cdi

###
GET http://localhost:8080/mp-restclient/builder

###
GET http://localhost:8080/mp-restclient/builder
CURL: TesteXPTO

###
GET http://localhost:8080/mp-restclient/async


###
OPTIONS http://localhost:8080/metrics/base
Accept: application/json

###
OPTIONS http://localhost:9080/metrics/base
Accept: application/json

###
OPTIONS http://localhost:8080/metrics/vendor
Accept: application/json


###
OPTIONS http://localhost:9080/metrics/vendor
Accept: application/json

###
GET http://localhost:8080/mp-metrics


###
GET http://localhost:9080/mp-metrics

###
GET http://localhost:8080/mp-metrics/tambem


###
GET http://localhost:9080/mp-metrics/tambem

###
GET http://localhost:8080/mp-metrics-copia


###
GET http://localhost:9080/mp-metrics-copia

###
GET http://localhost:8080/mp-metrics-copia/tambem


###
GET http://localhost:9080/mp-metrics-copia/tambem

###
GET http://localhost:8080/metrics/application
Accept: application/json


###
GET http://localhost:9080/metrics/application
Accept: application/json



