###
POST http://localhost:8080/municipios
Content-Type: application/json
Accept: application/json

{
    "nome": "Maceió",
    "populacao": 1230912
}

###
GET http://localhost:8080/municipios?idUF=2
Accept: application/json

Open Liberty
###
GET http://localhost:9080/municipios?idUF=2
Accept: application/json

###
GET http://localhost:8080/mp-restclient

###
GET http://localhost:8080/mp-restclient/sem-cdi

###
GET http://localhost:8080/mp-restclient/builder

###
GET http://localhost:8080/mp-restclient/builder
CURL: TesteXPTO

###
GET http://localhost:8080/mp-restclient/async